/* %%COPYRIGHT%% */

import "Unknwn.Idl";

cpp_quote("")
cpp_quote("/* %%COPYRIGHT%% */")
cpp_quote("")

cpp_quote("#if 0")
typedef struct _UNICODE_STRING {
    USHORT Length;
    USHORT MaximumLength;
#ifdef MIDL_PASS
    [size_is(MaximumLength / 2), length_is((Length) / 2)] USHORT * Buffer;
#else // MIDL_PASS
    _Field_size_bytes_part_(MaximumLength, Length) PWCH   Buffer;
#endif // MIDL_PASS
} UNICODE_STRING;
typedef UNICODE_STRING *PUNICODE_STRING;
typedef const UNICODE_STRING *PCUNICODE_STRING;

typedef enum _SECURITY_IMPERSONATION_LEVEL {
    SecurityAnonymous,
    SecurityIdentification,
    SecurityImpersonation,
    SecurityDelegation
} SECURITY_IMPERSONATION_LEVEL, *PSECURITY_IMPERSONATION_LEVEL;

typedef BOOLEAN SECURITY_CONTEXT_TRACKING_MODE, *PSECURITY_CONTEXT_TRACKING_MODE;

typedef struct _SECURITY_QUALITY_OF_SERVICE {
    ULONG Length;
    SECURITY_IMPERSONATION_LEVEL ImpersonationLevel;
    SECURITY_CONTEXT_TRACKING_MODE ContextTrackingMode;
    BOOLEAN EffectiveOnly;
} SECURITY_QUALITY_OF_SERVICE, *PSECURITY_QUALITY_OF_SERVICE;
cpp_quote("#endif")

#include "rpchelpi.idl"

cpp_quote("/*++")
cpp_quote("VOID")
cpp_quote("WINAPI")
cpp_quote("RaiseNonContinuableException(")
cpp_quote("    _In_ DWORD Code")
cpp_quote("    );")
cpp_quote("--*/")
cpp_quote("#define RaiseNonContinuableException(Code) \\")
cpp_quote("    RaiseException(Code, EXCEPTION_NONCONTINUABLE, 0, NULL)")
cpp_quote("")
cpp_quote("PXMIT_TYPE")
cpp_quote("WINAPI")
cpp_quote("XMITTYPE_TypeToXmit(")
cpp_quote("    _In_ ULONG Options,")
cpp_quote("    _In_opt_ CONST VOID *TypeData,")
cpp_quote("    _In_ ULONG Size")
cpp_quote("    );")
cpp_quote("")
cpp_quote("VOID")
cpp_quote("WINAPI")
cpp_quote("XMITTYPE_XmitToType(")
cpp_quote("    _In_ PXMIT_TYPE Xmit,")
cpp_quote("    _Out_ PVOID *Type")
cpp_quote("    );")
cpp_quote("")
cpp_quote("VOID")
cpp_quote("WINAPI")
cpp_quote("XMITTYPE_FreeType(")
cpp_quote("    _In_opt_ PVOID *Type")
cpp_quote("    );")
cpp_quote("")
cpp_quote("VOID")
cpp_quote("WINAPI")
cpp_quote("XMITTYPE_FreeXmit(")
cpp_quote("    _In_opt_ XMIT_TYPE *Xmit")
cpp_quote("    );")
cpp_quote("")
